/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UuidGeneratorLazyImport = createFileRoute('/uuid-generator')()
const ToDoListLazyImport = createFileRoute('/to-do-list')()
const DistanceCalculatorLazyImport = createFileRoute('/distance-calculator')()
const CounterLazyImport = createFileRoute('/counter')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UuidGeneratorLazyRoute = UuidGeneratorLazyImport.update({
  path: '/uuid-generator',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/uuid-generator.lazy').then((d) => d.Route),
)

const ToDoListLazyRoute = ToDoListLazyImport.update({
  path: '/to-do-list',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/to-do-list.lazy').then((d) => d.Route))

const DistanceCalculatorLazyRoute = DistanceCalculatorLazyImport.update({
  path: '/distance-calculator',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/distance-calculator.lazy').then((d) => d.Route),
)

const CounterLazyRoute = CounterLazyImport.update({
  path: '/counter',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/counter.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterLazyImport
      parentRoute: typeof rootRoute
    }
    '/distance-calculator': {
      id: '/distance-calculator'
      path: '/distance-calculator'
      fullPath: '/distance-calculator'
      preLoaderRoute: typeof DistanceCalculatorLazyImport
      parentRoute: typeof rootRoute
    }
    '/to-do-list': {
      id: '/to-do-list'
      path: '/to-do-list'
      fullPath: '/to-do-list'
      preLoaderRoute: typeof ToDoListLazyImport
      parentRoute: typeof rootRoute
    }
    '/uuid-generator': {
      id: '/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof UuidGeneratorLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  CounterLazyRoute,
  DistanceCalculatorLazyRoute,
  ToDoListLazyRoute,
  UuidGeneratorLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/counter",
        "/distance-calculator",
        "/to-do-list",
        "/uuid-generator"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/counter": {
      "filePath": "counter.lazy.tsx"
    },
    "/distance-calculator": {
      "filePath": "distance-calculator.lazy.tsx"
    },
    "/to-do-list": {
      "filePath": "to-do-list.lazy.tsx"
    },
    "/uuid-generator": {
      "filePath": "uuid-generator.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
