name: PR pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  pr_pipeline:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        node_version: ['18.12.0', '20.16.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: false
      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
